# Generated by Django 3.2 on 2022-06-12 21:51

import custom_django.models.fields.unix_timestamp
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('type', models.CharField(choices=[('F', 'Food'), ('G', 'Good')], default='G', max_length=1)),
                ('_created', custom_django.models.fields.unix_timestamp.UnixTimeStampField(auto_now_add=True, null=True)),
                ('_updated', custom_django.models.fields.unix_timestamp.UnixTimeStampField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Orderd'), ('P', 'Compleated'), ('C', 'Cancelled')], default='O', max_length=1)),
                ('amount', models.IntegerField()),
                ('_created', custom_django.models.fields.unix_timestamp.UnixTimeStampField(auto_now_add=True, null=True)),
                ('_updated', custom_django.models.fields.unix_timestamp.UnixTimeStampField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
    ]
